import test from 'node:test';
import assert from 'node:assert/strict';
import {CONFIG,WEIGHTS,makeWeights,forward,KVDecoder,softmax,layerNorm,positional,gelu,linear,dot,difference,compareRuns,random,traceJSON} from '../model.js';
const close=(a,b,tol=1e-11)=>assert.ok(Math.abs(a-b)<=tol,`${a} != ${b}`);
function compare(a,b){const d=compareRuns(a,b);assert.ok(d.logits<1e-11);assert.ok(d.probs<1e-11);for(let p=0;p<a.rows.length;p++){for(let l=0;l<2;l++){const x=a.rows[p].blocks[l],y=b.rows[p].blocks[l];for(const key of ['input','q','k','v','context','projected','residual1','ffPre','ffAct','ffOut','out'])assert.ok(difference(x[key],y[key])<1e-11,`${key}, p${p}, l${l}`);for(let h=0;h<2;h++)for(let j=0;j<=p;j++){close(x.heads[h].scores[j],y.heads[h].scores[j]);close(x.heads[h].probs[j],y.heads[h].probs[j]);}}}}
test('architecture and reproducible initialization',()=>{assert.deepEqual(WEIGHTS,makeWeights());assert.notDeepEqual(WEIGHTS,makeWeights(1));assert.equal(WEIGHTS.blocks.length,2);assert.equal(WEIGHTS.blocks[0].w1.length,16);assert.equal(WEIGHTS.blocks[0].w1[0].length,32);assert.equal(WEIGHTS.embedding.length,16);assert.equal(WEIGHTS.unembed.length,16);});
test('primitive math / stable softmax / population layer normalization',()=>{assert.deepEqual(linear([2,3],[[1,2],[4,5]]),[14,19]);assert.equal(dot([2,3],[4,5]),23);const p=softmax([1000,1001,-Infinity]);close(p[0],1/(1+Math.E));close(p[1],Math.E/(1+Math.E));assert.equal(p[2],0);assert.deepEqual(softmax([0,0]),[.5,.5]);const n=layerNorm([1,2,3,4]);close(n.mean,2.5);close(n.variance,1.25);close(n.value.reduce((a,b)=>a+b,0),0);assert.deepEqual(layerNorm(Array(16).fill(4)).value,Array(16).fill(0));close(gelu(0),0);close(gelu(1),.8411919906082768);assert.deepEqual(positional(0),Array.from({length:16},(_,i)=>i%2));close(positional(1)[2],Math.sin(1/Math.sqrt(10)));});
test('causal masking: exact zeros, normalized probabilities, no future leakage',()=>{const ids=[0,1,3,5,6,1,11,14],a=forward(ids),b=forward([...ids.slice(0,4),15,15,15,15]);for(let p=0;p<ids.length;p++){close(a.rows[p].probs.reduce((x,y)=>x+y,0),1);for(const block of a.rows[p].blocks)for(const h of block.heads){close(h.probs.reduce((x,y)=>x+y,0),1);assert.ok(h.probs.every(v=>v>=0&&v<=1));for(let j=p+1;j<ids.length;j++){assert.equal(h.probs[j],0);assert.equal(h.scores[j],-Infinity);}}if(p<4)assert.deepEqual(a.rows[p].logits,b.rows[p].logits);}});
test('cached / full equality at every prefix, every intermediate, every vocabulary output',()=>{const rng=random(718);for(let trial=0;trial<70;trial++){const ids=[],cache=new KVDecoder();for(let n=1;n<=CONFIG.maxContext;n++){ids.push(Math.floor(rng()*16));const c=cache.run(ids),f=forward(ids);assert.equal(c.computed,1);assert.equal(c.reused,n-1);compare(c,f);}}});
test('cache invalidates only the changed suffix; handles shrinking and same request',()=>{const c=new KVDecoder(),ids=[0,1,4,6,11];let a=c.run(ids);assert.equal(a.computed,5);const firstKey=c.cache[0].keys[0];a=c.run(ids);assert.equal(a.computed,0);assert.equal(a.reused,5);ids[2]=5;a=c.run(ids);assert.equal(a.computed,3);assert.equal(a.reused,2);assert.strictEqual(c.cache[0].keys[0],firstKey);compare(a,forward(ids));ids.length=3;a=c.run(ids);assert.equal(a.computed,0);assert.equal(a.reused,3);assert.equal(c.cache[1].keys.length,3);compare(a,forward(ids));ids.push(9,8);compare(c.run(ids),forward(ids));ids[0]=15;a=c.run(ids);assert.equal(a.reused,0);assert.equal(a.computed,5);compare(a,forward(ids));c.reset();assert.equal(c.cache[0].keys.length,0);});
test('attention output is actual weighted V; both residual paths and output projection',()=>{const a=forward([0,1,3,5]);for(const row of a.rows){for(let l=0;l<2;l++){const b=row.blocks[l];for(let h=0;h<2;h++)for(let d=0;d<8;d++)close(b.heads[h].context[d],b.heads[h].probs.reduce((s,p,j)=>s+p*a.rows[j].blocks[l].v[h*8+d],0));for(let d=0;d<16;d++){close(b.residual1[d],b.input[d]+b.projected[d]);close(b.out[d],b.residual1[d]+b.ffOut[d]);}}assert.deepEqual(row.logits,linear(row.final.value,WEIGHTS.unembed));}});
test('input validation is shared by both inference paths',()=>{for(const bad of [[],[16],[-1],[1.1],[NaN],Array(13).fill(0),null,'the']){assert.throws(()=>forward(bad));assert.throws(()=>new KVDecoder().run(bad));}const c=new KVDecoder();c.run([0]);assert.throws(()=>c.append(16));assert.deepEqual(c.ids,[0]);});
test('editing tokens changes actual predictions; no hardcoded output',()=>{assert.ok(difference(forward([0,1,4]).logits,forward([0,1,5]).logits)>.01);assert.ok(difference(forward([1,4]).logits,forward([4,1]).logits)>.01);});
test('export preserves the negative infinity mask',()=>{const data=JSON.parse(traceJSON(forward([0,1])));assert.equal(data.rows[0].blocks[0].heads[0].scores[1],'-Infinity');});
